-- 
SELECT DEPARTMENT_ID  , COUNT(*)
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID 
ORDER BY DEPARTMENT_ID
;

SELECT * FROM EMPLOYEES 
ORDER BY SALARY DESC ; 

SELECT * FROM EMPLOYEES 
ORDER BY FIRST_NAME DESC ; 

-- HOW ABOUT ORDERING BY COLUMN NUMBER RATHER THAN NAME 
-- IN SQL THERE AINT NO 0 INDEX , INDEX START WITH 1 
SELECT * FROM EMPLOYEES 
ORDER BY  2  DESC ; 


--- GETTING DISTINCT VALUE FROM THE TABLE 

--	1.1  GET UNIQUE MANAGER_IDs from Employees Table 

SELECT DISTINCT MANAGER_ID 
FROM EMPLOYEES ; 

-- FIND OUT UNIQUE FIRST_NAME IN EMPLOYEE TABLE 











