--- FIND OUT THE FIRST NAME AND DEPARTMENT NAME 
--- USE EMPLOYEES TABLE AND DEPARTMENT TABLE 

SELECT FIRST_NAME , DEPARTMENT_NAME
FROM EMPLOYEES 
INNER JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID ; 

-- ABOVE QUERY JUST WORK BUT ADDING TABLE NAME IN FRONT OF COLUYMN NAME ALL THE TIME IS NOT EFFICIENT 
-- WE CAN USE TABLE ALIASE TO MAKE THIS SIMPLER 

SELECT e.FIRST_NAME , d.DEPARTMENT_NAME 
FROM EMPLOYEES e                -- THIS IS HOW YOU PUT ALIASE FOR TABLE 
INNER JOIN DEPARTMENTS d ON e.Department_Id = d.DEPARTMENT_ID ; 


--- GET THE FIRST_NAME AND JOB_TITLE 
--- USE EMPLOYEES AND JOBS TABLE 
--- THE RELATIONSHIP JOB_ID 

SELECT e.FIRST_NAME , j.JOB_TITLE 
FROM EMPLOYEES e 
INNER JOIN JOBS j on e.JOB_ID = j.JOB_ID ; 

-- FIRST_NAME , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME 

SELECT e.FIRST_NAME , d.DEPARTMENT_NAME , l.CITY , c.COUNTRY_NAME , r.REGION_NAME 
FROM EMPLOYEES e 
INNER JOIN DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID
INNER JOIN LOCATIONS l on l.LOCATION_ID = d.LOCATION_ID
INNER JOIN COUNTRIES c on l.COUNTRY_ID = c.COUNTRY_ID
INNER JOIN REGIONS r   on c.REGION_ID = r.REGION_ID ; 










