-- SET OPERATORS 
-- UNION ALL , UNION , MINUS , INTERSECT 

-- RUN THIS ONLY ONCE BY SELECTING FROM HERE TILL COMMIT ; 
CREATE TABLE FIRST_TABLE AS (
    SELECT FIRST_NAME , SALARY FROM EMPLOYEES 
    WHERE SALARY BETWEEN 10500 AND 13000
    
) ORDER BY 2 ;  

SELECT * FROM first_table;

CREATE TABLE SECOND_TABLE AS (
    SELECT FIRST_NAME , SALARY FROM EMPLOYEES 
    WHERE SALARY BETWEEN 12000 AND 24000
    
) ORDER BY 2 ;  

COMMIT ; 

----------

SELECT * FROM FIRST_TABLE 
UNION ALL 
SELECT * FROM SECOND_TABLE;


-- UNION = 
-- COMBINE THE RESULT OF 2 QUERY AND WILL REMOVE DUPLICATE WILL SORT BY FIRST COLUMN 
-- DUPLICATE HERE MEANS ROW LEVEL DUPLICATION , 
--- IF 2 ROWS ARE DUPLICATE , ALL COLUMNS VALUE MUST BE THE SAME 
SELECT * FROM FIRST_TABLE 
UNION 
SELECT * FROM SECOND_TABLE  ; 


SELECT * FROM FIRST_TABLE 
MINUS 
SELECT * FROM SECOND_TABLE ; 

SELECT * FROM SECOND_TABLE 
MINUS 
SELECT * FROM FIRST_TABLE ; 


SELECT * FROM FIRST_TABLE 
INTERSECT 
SELECT * FROM SECOND_TABLE ; 
-- LIST 1  : APPLE , EGG , MILK , PINEAPPLE, BREAD
-- LIST 2  : MILK , BREAD , OIL , WALNUT

-- UNION ALL -->> APPLE , EGG , MILK , PINEAPPLE, BREAD , MILK , BREAD , OIL , WALNUT
-- UNION     -->> APPLE , BREAD , EGG, MILK, PINEAPPLE , OIL , WALNUT 


-- LIST 1  MINUS LIST 2 
 -- LIST 2 HERE IS NO-NO LIST 
  
  -- MINUS   --> APPLE , EGG , PINEAPPLE
  
-- LIST2 MINUS LIST 1 
  -- LIST 1 HERE IS NO-NO LIST 
    
  -- MINUS -->>   OIL , WALNUT 


 --- INTERSECT 
    -- LIST 1 INTERSECT LIST 2 
        --->> ONLY COMMON PART OF BOTH LIST  -->> MILK , BREAD



