-- this is how you comment 
-- double hypen is comment in SQL 
-- SQL most of the time is case insensitive 

-- * is wildcard , means all the columns 
SELECT * FROM EMPLOYEES ; 
-- YOU CAN ONLY USE THE TABLE THAT EXISTS 
-- OR IT WILL GIVE YOU ERROR 
SELECT * FROM COUNTRIES ; 

-- TASK 1 : 
-- USING ABOVE EXAMPLE , SEE ALL DATA FROM ALL OTHER TABLES 
SELECT * FROM DEPARTMENTS ; 
SELECT * FROM JOBS ; 
SELECT * FROM LOCATIONS ; 
SELECT * FROM JOB_HISTORY ; 
SELECT * FROM REGIONS ; 

-- SELECTING SPECIFIC COLUMN RATHER THAN ALL OF THEM FROM A TABLE 
-- YOU CAN USE COLUMN NAME SEPERATED BY COMMA TO GET ONLY COLUMNS YOU CARE ABOUT 

SELECT FIRST_NAME , SALARY 
FROM EMPLOYEES ; 

-- TASK 2 :  SHOW THE RESULT OF ALL LAST_NAME , HIRE_DATE , DEPARTMENT_ID
SELECT LAST_NAME , HIRE_DATE , DEPARTMENT_ID
FROM EMPLOYEES ; 
-- WHITE SPACE DOES , MAKE IT AS MUCH READABLE AS POSSIBLE WITH YOUR IMAGINATION

/*
THIS IS HOW YOU DO MULTI LINE COMMENT 
NOW SELECT THESE COLUMNS FROM LOCATIONS TABLE 
    STREET_ADDRESS
    CITY
    STATE_PROVINCE
*/
SELECT STREET_ADDRESS, CITY, STATE_PROVINCE
FROM LOCATIONS ; 
